name: Maximum Enjoyment
favicon: null
layout_spectrum: 0.25211789086461067
typography_spectrum: 0.861132672522217
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4944017331581563
  lightness: 0.41174398036673665
  saturation: 0.9206971037201583
  rhythmicContrast: 0.7884135597851127
purpose: []
